name: Build and Deploy to Cloud Functions

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  RUN_REGION: us-central1
  SERVICE_NAME: helloworld-nodejs

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '296.0.1'
        service_account_key: ${{ secrets.RUN_SA_KEY }}
        project_id: ${{ secrets.RUN_PROJECT }}

    # Deploy image to Cloud Run
    - run: gcloud info
    - run: gcloud auth list
    - run: find .
    - name: Deploy
    - run: >-
        gcloud functions deploy test-pub-sub
        --region=europe-west2
        --entry-point=hello_pubsub
        --update-labels githubaction=$GITHUB_ACTION
        --source=test-pub-sub