name: Integration and Deploy to Cloud Functions

on: [push]

env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  RUN_REGION: us-central1
  SERVICE_NAME: helloworld-nodejs

jobs:
  integration-test:
    name: Integration test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '296.0.1'
        service_account_key: ${{ secrets.RUN_SA_KEY }}
        project_id: ${{ secrets.RUN_PROJECT }}
        export_default_credentials: true
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -e .
    - name: Integration tests
      run: pytest tests/integration      

  deploy:
    name: Deploy to GCloud
    runs-on: ubuntu-latest

    needs: integration-test
    if: github.ref == 'refs/heads/master'

    steps:
    # Deploy image to Cloud Run
    - run: gcloud info
    - run: gcloud auth list
    - run: find .
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '296.0.1'
        service_account_key: ${{ secrets.RUN_SA_KEY }}
        project_id: ${{ secrets.RUN_PROJECT }}
    - name: Deploy
      run: >-
        gcloud functions deploy generateplaylist 
        --region=europe-west2
        --entry-point=generateplaylist 
        --update-labels githubaction=$GITHUB_ACTION
        --source=src/

    # - name: Deploy
    #   run: >-
    #     gcloud functions deploy test-pub-sub
    #     --region=europe-west2
    #     --entry-point=hello_pubsub
    #     --update-labels githubaction=$GITHUB_ACTION
    #     --source=src/
        
    
